# 공통 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    hibernate:
      ddl-auto: update    # 실행시 DB 초기화 후 DDL 실행
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 보기 좋게 표시
        show_sql: true    # SQL 쿼리 확인

  datasource:
    url: jdbc:mariadb://localhost:3306/s09p22c105
    username: ${DB_ID}
    password: ${DB_PW}

  sql:
    init:
      encoding: UTF-8

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    hibernate:
      ddl-auto: none      # 실행시 DB 그대로
    properties:
      hibernate:
        format_sql: false # SQL 쿼리 보기 좋게 표시 X
        show_sql: false   # SQL 쿼리 확인 X

  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P22C105
    username: ${DB_ID}
    password: ${DB_PW}

  sql:
    init:
      encoding: UTF-8